# Site settings
title: Dave Stagner
email: dave@congruence.io
description: > 
  Software, music, and other ideas. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davestagner.com" # the base hostname & protocol for your site
twitter_username: davestagner
github_username:  dstagner

# Build settings
markdown: kramdown

paginate: 5

gems: [jekyll-paginate]

# Disqus Comments
disqus_short_name: davestagner
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-40292660-1
